#ifndef PROTOTYPE_2_CONFIG_H
#define PROTOTYPE_2_CONFIG_H
// This is the config file for prototype2

/* ENDIANNESS */
#define PRT_BIG_ENDIAN 1

/* VERSION */
#define prototype2_VERSION_MAJOR 1
#define prototype2_VERSION_MINOR 0

/* PATHS */
#define RESOURCE_PATH "/Users/arnestenkrona/Documents/repositories/prototype2/res/"

/* MEMORY */
#define DEFAULT_CONTAINER_ALLOCATOR_SIZE_BYTES 64*1024*1024
#define DEFAULT_CONTAINER_ALLOCATOR_BLOCK_SIZE_BYTES 256
#define DEFAULT_CONTAINER_ALLOCATOR_ALIGNMENT_BYTES 4

/* GRAPHICS */
#define NUMBER_SUPPORTED_TEXTURES 64
#define NUMBER_SUPPORTED_BILLBOARD_TEXTURES 8
#define NUMBER_SUPPORTED_MODEL_MATRICES 100 
#define NUMBER_SUPPORTED_BILLBOARDS 200
#define NUMBER_SUPPORTED_POINTLIGHTS 4
#define NUMBER_SUPPORTED_BOXLIGHTS 20
#define NUMBER_SHADOWMAP_CASCADES 3
#define NUMBER_MAX_BONES 100

/* GAME */
#define FRAME_RATE 60

#endif
